=== 549919020/dumi_doc/dumi_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id":"https://xiaodu.baidu.com/schema/dumi_schema.json",
    "title":"度秘ws的返回值",
    "type": "object",
    "properties": {
        "result": {
            "type":"object",
            "properties":{
                "hint":{
                    "description":"用户接下去可以输入的query建议",
                    "type":"array",
                    "items": { "type": "string" }
                },
                "cards":{
                    "description":"展示用的卡片",
                    "$ref":"#/definitions/cards"
                },
                "directives":{
                    "description":"展示用的卡片",
                    "$ref":"#/definitions/directives"
                },
                "resource":{
                    "description":"数据资源",
                    "$ref":"#/definitions/resource"
                },
                "intent":{
                    "description":"使用的da结果",
                    "$ref":"#/definitions/intent"
                },
                "speech":{
                    "description":"语音播报tts用的数据",
                    "$ref":"#/definitions/speech"
                }
            },
            "required": ["cards","speech","intent"],
            "additionalProperties":false
        },
        "ctime": {
            "type":"integer"
        },
        "cuid": {
            "type":"string"
        },
        "user_id": {
            "type":"string"
        },
        "id": {
            "type":"string"
        },
        "logid": {
            "type":"string"
        },
        "se_query": {
            "type":"string"
        },
        "status": {
            "type":"integer"
        },
        "msg": {
            "type":"string"
        }
    },
    "definitions": {
        "directives": {
            "type":"object",
            "properties":{
            }
        },
        "resource": {
            "type":"object",
            "oneOf":[
                {"$ref":"weather.schema.json"},
                {"$ref":"news.schema.json"}
            ]
        },
        "intent": {
            "type":"object",
            "properties":{
            }
        },
        "cards": {
            "type":"object",
            "properties":{
            }
        },
        "speech": {
            "type":"object",
            "properties":{
                "type":{
                    "type":"string",
                    "enum":["Text","SSML"]
                },
                "content":{
                    "type":"string"
                }
            }
        }
    },
    "additionalProperties": false,
    "required": [ "result","ctime","id","cuid","logid","se_query","status","msg"]
}

=== 549919020/dumi_doc/test.json
{
    "status":0,
    "msg":"ok",
    "se_query":"原始query", 
    "logid":"xxxx1234354", 
    "id":"id12334235",
    "user_id":"",
    "cuid":"",
    "ctime":1482226019,
    "result":{
        "cards":{},
        "intent":{},
        "speech": {
            "type": "Text",  
            "content": "为您播放周杰伦的歌曲"
        }
    }
}

=== 549919020/dumi_doc/testdata/weather.json
{
    "status":0,
    "msg":"ok",
    "se_query":"原始query", 
    "logid":"xxxx1234354", 
    "id":"id12334235",
    "user_id":"",
    "cuid":"",
    "ctime":1482226019,
    "result":{
        "cards":{},
        "intent":{},
        "resource":{
            "type":"weather",
            "data":{
                "city": "北京",
                "current_temp": "-1℃",
                "pm25": "426",
                "temp": "-3℃~5℃",
                "time": "周二 12月20日",
                "weather": "雾",
                "weather_all": "雾，-3℃~5℃，微风",
                "wind": "微风",
                "weather_info": [
                    {
                        "current_temp": "-1℃",
                        "icon": "http://s1.bdstatic.com/r/www/aladdin/img/new_weath/bigicon/4.png",
                        "pm25": "426",
                        "pm_level": "严重污染",
                        "temp": "-3℃~5℃",
                        "time": "周二 12月20日",
                        "weather": "雾",
                        "wind": "微风"
                    },
                    {
                        "icon": "http://s1.bdstatic.com/r/www/aladdin/img/new_weath/icon/7.png",
                        "temp": "-3℃~3℃",
                        "time": "周三 12月21日",
                        "weather": "霾",
                        "wind": "微风"
                    },
                    {
                        "icon": "http://s1.bdstatic.com/r/www/aladdin/img/new_weath/icon/1.png",
                        "temp": "-5℃~6℃",
                        "time": "周四 12月22日",
                        "weather": "晴",
                        "wind": "北风3-4级"
                    },
                    {
                        "icon": "http://s1.bdstatic.com/r/www/aladdin/img/new_weath/icon/1.png",
                        "temp": "-6℃~3℃",
                        "time": "周五 12月23日",
                        "weather": "晴转多云",
                        "wind": "北风微风"
                    },
                    {
                        "icon": "http://s1.bdstatic.com/r/www/aladdin/img/new_weath/icon/5.png",
                        "temp": "-5℃~3℃",
                        "time": "周六 12月24日",
                        "weather": "多云转霾",
                        "wind": "北风微风"
                    }
                ]
            }
        },
        "speech": {
            "type": "Text",  
            "content": "为您播放周杰伦的歌曲"
        }
    }
}
