=== 549919020/dumi_doc/schema/appid.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id":"https://xiaodu.baidu.com/schema/appid.json",
    "title":"appid的定义，包含appid对bots的映射",
    "type":"array",
    "items":{
        "type":"object",
        "properties":{
            "bots":{
                "type":"array",
                "items":{
                    "type":"object",
                    "properties":{
                        "params":{"type":"object","description":"请求bot带上的参数，不作限制"},
                        "version":{"type":"string","description":"请求bot的指定版本，默认可填0，就是最新版本"},
                        "id":{"type":"string"}
                    }
                }
            },
            "appname":{"type":"string"},
            "appid":{"type":"string"},
            "appkey":{"type":"string"},
            "qps":{"type":"integer","description":"每秒最大请求次数"},
            "qpd":{"type":"integer","description":"每天最大请求次数"},
            "ctime":{"type":"integer","description":"创建时间，unix时间戳"},
            "strategy":{"type":"string","description":"排序策略"},
            "version":{"type":"string","description":"客户端版本，一个客户端可按客户端版本不同，存在多份配置"}
        }
    }
}

=== 549919020/dumi_doc/testdata/platform/appid_bots.json
[
    {
        "appname":"小米手机助手",
        "appid":"xxxxx",
        "appkey":"yyyy",
        "qps":50,
        "qpd":500000,
        "ctime":1474283539,
        "strategy":"xiaomi",
        "version":"1.0.0",
        "bots":[
            {"id":"talk_service","version":"1.0.0"},
            {"id":"aries_general","version":"1.0.0"},
            {"id":"movie_satisfy","version":"1.0.0"},
            {"id":"light_vertical","version":"1.0.0"},
            {"id":"recommend_service_wireless","version":"1.0.0","params":{"joke_type":1}},
            {"id":"restaurant_bot","version":"1.0.0"}
        ]
    },
    {
        "appname":"小米手机助手",
        "appid":"xxxxx1",
        "appkey":"yyyy1",
        "qps":0,
        "qpd":0,
        "ctime":1474283539,
        "strategy":"xiaomi",
        "version":"1.0.0",
        "bots":[
            {"id":"talk_service","version":"1.0.0"},
            {"id":"aries_general","version":"1.0.0"},
            {"id":"movie_satisfy","version":"1.0.0"},
            {"id":"light_vertical","version":"1.0.0"},
            {"id":"recommend_service_wireless","version":"1.0.0","params":{"joke_type":1}},
            {"id":"restaurant_bot","version":"1.0.0"}
        ]
    }
]
