=== 549919020/dumi_doc/schema/bots.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id":"https://xiaodu.baidu.com/schema/bots.json",
    "title":"bot列表的定义",
    "type":"array",
    "items":{
        "type":"object",
        "required":["id","server"],
        "properties":{
            "id":{"type":"string"},
            "is_session_enable":{"type":"integer"},
            "is_uic_enable":{"type":"integer"},
            "is_base_uic_enable":{"type":"integer"},
            "private_field":{
                "description":"这个估计是调用用户画像服务的参数",
                "type":"array",
                "items":{"type":"string"}
            },
            "server":{
                "oneOf":[
                    {"$ref":"#/definitions/ipport_server"},
                    {"$ref":"#/definitions/bns_server"}
                ]
            },
            "sessions":{
                "type":"array",
                "items":{
                    "type":"object",
                    "properties":{
                        "name":{"type":"string"},
                        "type":{"type":"string","enum":["string","list","hash"]},
                        "private":{"type":"integer","enum":[0,1]}
                    }
                }
            }
        }
    },
    "definitions": {
        "ipport_server":{
            "type":"object",
            "required":["machine","protocal","type"],
            "properties":{
                "machine":{
                    "type":"array",
                    "items":{
                        "type":"object",
                        "required":["ip","port"],
                        "properties":{
                            "ip":{"type":"string"},
                            "port":{"type":"integer"}
                        }
                    }
                },
                "protocal":{"type":"string","enum":["http","http_post","mcpack"]},
                "type":{"type":"string","enum":["ipport"]}
            }
        },
        "bns_server":{
            "type":"object",
            "required":["protocal","bns_node_name","type"],
            "properties":{
                "protocal":{"type":"string","enum":["http","http_post","mcpack"]},
                "bns_node_name":{"type":"string"},
                "bns_timeout": {"type":"integer","description":"单位是毫秒"},
                "bns_node_info_file":{"type":"string","description":"TODO 文件名，还不知道是干什么的，晓鸣也不知道"},
                "type":{"type":"string","enum":["bns"]}
            }
        }
    }

}

=== 549919020/dumi_doc/schema/testdata/platform/bots.json
[
    {
        "id":"talk_service",
        "is_session_enable":1,
        "is_uic_enable":1,
        "is_base_uic_enable":1,
        "private_field":["identity","family_name"],
        "server":{
            "type":"bns",
            "protocal":"mcpack",
            "bns_node_name": "",
            "bns_timeout": 1000,
            "bns_node_info_file":"sac_dumi_nj.file"
        },
        "sessions":[
            {
                "name":"dumi_decision_info",
                "type":"string",
                "private":0
            },
            {
                "name":"phone",
                "type":"string",
                "private":1
            }
        ]
    },
    {
        "id":"phone",
        "is_session_enable":1,
        "is_uic_enable":1,
        "is_base_uic_enable":1,
        "server":{
            "type":"ipport",
            "protocal":"http",
            "machine":[
                {
                    "ip":"1.2.3.4",
                    "port":1234
                }
            ]
        },
        "sessions":[
            {
                "name":"phone",
                "type":"hash",
                "private":1
            }
        ]
    }
]
